/** Common IANA timezone options shown in the notification settings picker. */
export const NOTIFICATION_TIMEZONES = [
  { value: 'Pacific/Honolulu',    text: 'Honolulu - Hawaiian Time (UTC-10:00)' },
  { value: 'America/Anchorage',   text: 'Anchorage - Alaska Time (UTC-09:00)' },
  { value: 'America/Los_Angeles', text: 'Los Angeles - Pacific Time (UTC-08:00)' },
  { value: 'America/Denver',      text: 'Denver - Mountain Time (UTC-07:00)' },
  { value: 'America/Chicago',     text: 'Chicago - Central Time (UTC-06:00)' },
  { value: 'America/New_York',    text: 'New York - Eastern Time (UTC-05:00)' },
  { value: 'America/Halifax',     text: 'Halifax - Atlantic Time (UTC-04:00)' },
  { value: 'America/Sao_Paulo',   text: 'São Paulo - Brasília Time (UTC-03:00)' },
  { value: 'Atlantic/Azores',     text: 'Azores - Azores Time (UTC-01:00)' },
  { value: 'Europe/London',       text: 'London - Greenwich Mean Time (UTC+00:00)' },
  { value: 'Europe/Paris',        text: 'Paris - Central European Time (UTC+01:00)' },
  { value: 'Europe/Helsinki',     text: 'Helsinki - Eastern European Time (UTC+02:00)' },
  { value: 'Europe/Moscow',       text: 'Moscow - Moscow Standard Time (UTC+03:00)' },
  { value: 'Asia/Dubai',          text: 'Dubai - Gulf Standard Time (UTC+04:00)' },
  { value: 'Asia/Karachi',        text: 'Karachi - Pakistan Standard Time (UTC+05:00)' },
  { value: 'Asia/Kolkata',        text: 'Mumbai - Indian Standard Time (UTC+05:30)' },
  { value: 'Asia/Dhaka',          text: 'Dhaka - Bangladesh Standard Time (UTC+06:00)' },
  { value: 'Asia/Bangkok',        text: 'Bangkok - Indochina Time (UTC+07:00)' },
  { value: 'Asia/Singapore',      text: 'Singapore - Singapore Standard Time (UTC+08:00)' },
  { value: 'Asia/Tokyo',          text: 'Tokyo - Japan Standard Time (UTC+09:00)' },
  { value: 'Australia/Sydney',    text: 'Sydney - Australian Eastern Time (UTC+10:00)' },
  { value: 'Pacific/Auckland',    text: 'Auckland - New Zealand Standard Time (UTC+12:00)' },
  { value: 'UTC',                 text: 'UTC - Coordinated Universal Time (UTC+00:00)' },
];
